# Generated by Django 4.1.5 on 2023-02-07 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_incoming_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming_info',
            name='roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.contact_info', to_field='roll'),
        ),
    ]
