# Generated by Django 4.1.5 on 2023-02-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_incoming_info_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_info',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
