# Generated by Django 4.1.5 on 2023-02-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_remove_contact_info_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming_info',
            name='date_time',
            field=models.DateTimeField(default='1111-11-11'),
        ),
    ]
