# Generated by Django 4.1.3 on 2023-06-05 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_alter_relation_users_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='friend_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='security.contact_info', to_field='roll')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='security.contact_info', to_field='roll')),
            ],
        ),
    ]
