# Generated by Django 4.1.3 on 2023-06-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0012_friend_requests_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend_requests',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
