# Generated by Django 4.1.5 on 2023-02-07 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='incoming_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate_x', models.CharField(max_length=354)),
                ('coordinate_y', models.CharField(max_length=354)),
                ('emergency', models.BooleanField()),
                ('roll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='security.contact_info', to_field='roll')),
            ],
        ),
    ]
