# Generated by Django 4.1.5 on 2023-02-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_alter_contact_info_email_alter_contact_info_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_info',
            name='date_time',
            field=models.DateTimeField(default='1111-11-11 00:00:00'),
        ),
    ]
