# Generated by Django 4.1.5 on 2023-02-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_contact_info_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_info',
            name='date_time',
        ),
    ]
