# Generated by Django 4.1.5 on 2023-02-10 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_incoming_info_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='relation_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='security.contact_info', to_field='roll')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='security.contact_info', to_field='roll')),
            ],
        ),
    ]
